name: kifah
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0-215.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  fluttertoast: 
  flutter_overboard: 
  page_transition: 
  shared_preferences: 
  clipboard: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pflag2.png"  


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

 
  assets:
    - assets/images/pflag.png
    - assets/images/pflag2.png
    - assets/images/savep.png
    - assets/images/راية_العقاب 1.png
    - assets/images/Vector.png

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf 
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Bold.ttf 
  
